apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: {{ quote .Values.name }}
    version: {{ quote .Values.deploymentVersion }}
  name: {{ quote .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ quote .Values.name }}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ quote .Values.name }}
    spec:
      containers:
      - name: {{ quote .Values.name }}
        image: microservice-istio-{{ .Values.name }}:{{ .Values.imageVersion }}
        imagePullPolicy: Never
        ports:
        - containerPort: {{ .Values.port }}
        resources: {}
status: {}